# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.18"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.18"
  i386: "ghcr.io/home-assistant/i386-base-python:3.11-alpine3.18"
labels:
  org.opencontainers.image.title: "SimulIoT: Enable virtual devices to test-drive your IoT deployments!"
  org.opencontainers.image.description: "With this add-on, you can try out the functionality of Home Assistant without having to buy any hardware. This add-on is also useful for testing your own custom components and automations."
  org.opencontainers.image.source: "https://github.com/KenethRE/TFG-IoTSim"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
