# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SimulIoT
version: "0.0.6"
slug: simuliot
description: This add-on allows you to simulate IoT devices.
url: "https://github.com/KenethRE/TFG-IoTSim"
ingress: true
ingress_port: 8087
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/kenethre/{arch}-simuliot"
