# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SimulIoT
version: "0.0.20"
slug: simuliot
description: This add-on allows you to simulate IoT devices.
url: "https://github.com/KenethRE/TFG-IoTSim"
webui: http://[HOST]:[PORT:8099]
hassio_api: true
hassio_role: homeassistant
homeassistant_api: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "This is a test"
schema:
  message: "str?"
ports:
  8099/tcp: 8099
services:
  - mqtt:need

#image: "ghcr.io/kenethre/{arch}-simuliot"
