# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SimulIoT
version: "0.0.3"
slug: simuliot
description: This add-on allows you to simulate IoT devices.
url: "https://github.com/KenethRE/TFG-IoTSim"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/KenethRE/{arch}-simuliot:{version}"
