# Generated by Django 5.0.2 on 2024-02-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starthere', '0002_plano_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='Subir_Plano',
            field=models.ImageField(upload_to='images/maps/'),
        ),
    ]
