# Generated by Django 5.0.2 on 2024-02-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starthere', '0003_alter_plano_subir_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='Subir_Plano',
            new_name='Upload_Map',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='Nombre_Imagen',
        ),
    ]
