# Generated by Django 5.0.2 on 2024-02-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starthere', '0004_rename_subir_plano_plano_upload_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceID', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
