# Generated by Django 5.0.2 on 2024-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starthere', '0006_devices_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='Location',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
